<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SearchService</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
    <PackageReference Include="MassTransit" Version="8.5.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SearchService.Domain/SearchService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
